import { StatusCodes, ReasonPhrases } from "http-status-codes";

export const {
  OK,
  CREATED,
  ACCEPTED,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  UNPROCESSABLE_ENTITY,
  INTERNAL_SERVER_ERROR,
  NOT_IMPLEMENTED,
  SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT,
} = StatusCodes;

export const {
  OK: OK_REASON,
  CREATED: CREATED_REASON,
  ACCEPTED: ACCEPTED_REASON,
  NO_CONTENT: NO_CONTENT_REASON,
  BAD_REQUEST: BAD_REQUEST_REASON,
  UNAUTHORIZED: UNAUTHORIZED_REASON,
  FORBIDDEN: FORBIDDEN_REASON,
  NOT_FOUND: NOT_FOUND_REASON,
  CONFLICT: CONFLICT_REASON,
  UNPROCESSABLE_ENTITY: UNPROCESSABLE_ENTITY_REASON,
  INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR_REASON,
  NOT_IMPLEMENTED: NOT_IMPLEMENTED_REASON,
  SERVICE_UNAVAILABLE: SERVICE_UNAVAILABLE_REASON,
  GATEWAY_TIMEOUT: GATEWAY_TIMEOUT_REASON,
} = ReasonPhrases;
